//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIBRARY_DATABASEEntities7 : DbContext
    {
        public LIBRARY_DATABASEEntities7()
            : base("name=LIBRARY_DATABASEEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT_INFO> CLIENT_INFO { get; set; }
        public virtual DbSet<REQUEST_FORM> REQUEST_FORM { get; set; }
    }
}
