//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIBRARY_DATABASEEntities : DbContext
    {
        public LIBRARY_DATABASEEntities()
            : base("name=LIBRARY_DATABASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKS_MANAGEMENT> BOOKS_MANAGEMENT { get; set; }
        public virtual DbSet<STAFF_ACCOUNT> STAFF_ACCOUNT { get; set; }
    }
}
