//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class READER_INF : activeAccountDTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public byte[] AVATAR { get; set; }
        public string READERID { get; set; }
        public string PID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public Nullable<byte> AGE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_FORM> REQUEST_FORM { get; set; }

        public READER_INF()
        {

        }

        public READER_INF(string username, string pass)
        {
            this.REQUEST_FORM = new HashSet<REQUEST_FORM>();
        }

        public READER_INF(DataRow source)
        {

        }
    }
}
