//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class READER_INF : activeAccountDTO
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public byte[] AVATAR { get; set; }
        public string READERID { get; set; }
        public string PID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public Nullable<byte> AGE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string NOTE { get; set; }
    
        public virtual ICollection<REQUEST_FORM> REQUEST_FORM { get; set; }

        public READER_INF()
        {

        }

        public READER_INF(string username, string pass, string name = "")
        {
            USERNAME = username;
            PASSWORD = pass;
            NAME = name;
        }

        public READER_INF(DataRow source)
        {
            USERNAME = source[0].ToString();
            PASSWORD = source[1].ToString();
            AVATAR = (byte[])source[2];
            READERID = source[3].ToString();
            PID = source[4].ToString();
            NAME = source[5].ToString();
            SEX = source[6].ToString();
            BIRTH = Convert.ToDateTime(source[7]);
            AGE = Convert.ToByte(source[8]);
            ADDRESS = source[9].ToString();
            PHONE = source[10].ToString();
            EMAIL = source[11].ToString();
            EMAIL = source[11].ToString();
            NOTE = source[12].ToString();
        }
    }
}
