//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_FORM
    {
        public string ID { get; set; }
        public int REQUEST_ID { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string STATUS { get; set; }
    
        public virtual REQUEST_INFO REQUEST_INFO { get; set; }
    }
}
