//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_FORM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUEST_FORM()
        {
            this.REQUEST_INFO = new HashSet<REQUEST_INFO>();
        }
    
        public string REQUEST_ID { get; set; }
        public string USERID { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_INFO> REQUEST_INFO { get; set; }
    }
}
