//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUEST_INFO()
        {
            this.REQUEST_FORM = new HashSet<REQUEST_FORM>();
        }
    
        public int REQUEST_ID { get; set; }
        public Nullable<int> BOOKS_ID { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<int> NUMBER { get; set; }
    
        public virtual BOOKS_MANAGEMENT BOOKS_MANAGEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_FORM> REQUEST_FORM { get; set; }
    }
}
