//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHARED_LIBRARY_ENTITY : DbContext
    {
        public SHARED_LIBRARY_ENTITY()
            : base("name=SHARED_LIBRARY_ENTITY")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<READER_INF> READER_INF { get; set; }
        public virtual DbSet<BOOKS_MANAGEMENT> BOOKS_MANAGEMENT { get; set; }
        public virtual DbSet<EBOOKS_MANAGEMENT> EBOOKS_MANAGEMENT { get; set; }
        public virtual DbSet<REQUEST_FORM> REQUEST_FORM { get; set; }
        public virtual DbSet<REQUEST_INFO> REQUEST_INFO { get; set; }
        public virtual DbSet<STAFF_INF> STAFF_INF { get; set; }
    }
}
