//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_ACCOUNT
    {
        public string ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual STAFF_INFO STAFF_INFO { get; set; }
    }
}
