//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class STAFF_INF : activeAccountDTO
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public byte[] AVATAR { get; set; }
        public string STAFFID { get; set; }
        public string PID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public Nullable<byte> AGE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> TYPE { get; set; }
        public string NOTE { get; set; }

        public STAFF_INF() { }

        public STAFF_INF(string _USERNAME, string _PASSWORD, string _NAME = "Unnamed User")
        {
            USERNAME = _USERNAME;
            PASSWORD = _PASSWORD;
            NAME = _NAME;
            TYPE = false;
        }

        public STAFF_INF(DataRow source)
        {
            bool _TYPE = Convert.ToBoolean(source[12]);

            USERNAME = source[0].ToString();
            PASSWORD = source[1].ToString();
            AVATAR = (byte[])source[2];
            STAFFID = source[3].ToString();
            PID = source[4].ToString();
            NAME = source[5].ToString();
            SEX = source[6].ToString();
            BIRTH = Convert.ToDateTime(source[7]);
            AGE = Convert.ToByte(source[8]);
            ADDRESS = source[9].ToString();
            PHONE = source[10].ToString();
            EMAIL = source[11].ToString();
            EMAIL = source[11].ToString();
            TYPE = _TYPE != null ? _TYPE : false;
            NOTE = source[13].ToString();
        }
    }
}
