//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien.DTO
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class STAFF_INF : activeAccountDTO
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public byte[] AVATAR { get; set; }
        public string STAFFID { get; set; }
        public string PID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public Nullable<byte> AGE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> TYPE { get; set; }
        public string NOTE { get; set; }

        public STAFF_INF()
        {

        }
        public STAFF_INF(DataRow source)
        {

        }
    }
}
