//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBOOKS_MANAGEMENT
    {
        public int SERIAL_NUMBER { get; set; }
        public string CATEGORY { get; set; }
        public string LANGUAGE { get; set; }
        public string TITLE { get; set; }
        public string AUTHOR { get; set; }
        public string PUBLISHER { get; set; }
        public Nullable<int> YEAROFPUB { get; set; }
        public string NOTE { get; set; }
        public string BOOK_URL { get; set; }
        public string IMAGES_URL { get; set; }
    }
}
